### PR TITLE
recruit.md: Reorganize 2020-recruit as archive.

### PR DESCRIPTION
**Pull request by atamaokac**

### CODE REVIEW

**Review by 0one23 — DISMISSED** [review]

**Review by takyamamoto — DISMISSED** [review]
OK

**Comment by takyamamoto** [comment]
Sorry, conflict emerged.

**Comment by atamaokac** [comment]
@takyamamoto Corrected. Thanks!

**Review by takyamamoto — APPROVED** [review]
OK. Thanks!

**Pull request merged**
