### PR TITLE
Centering of images

### PR DESCRIPTION
**Pull request by takyamamoto**
I made images center to look well.

### CODE REVIEW

**Comment by atamaokac** [comment]
It does not seem to be working. (I checked the activities page on Chrome.)

**Comment by takyamamoto** [comment]
I added `!important`

**Comment by atamaokac** [comment]
Still not working...

**Comment by takyamamoto** [comment]
Hmm...
In my Dev tool, it works.

## Before
image


## After
image

**Comment by atamaokac** [comment]
Sorry..., it works. After rebooting, I've come to see it correctly on my test environment. The 17:18 version works, so I think you can revert the 18:09 patch.

**Comment by takyamamoto** [comment]
I reverted. Please check

**Pull request merged**
