### PR TITLE
New blog article: Neural tangents

### PR DESCRIPTION
**Pull request by takyamamoto**
I write a new article which is first in 2020sy.

### CODE REVIEW

**Comment by takyamamoto** [comment]
ipynb notebooks are difficult to check their contents... (but please check)

**Comment by atamaokac** [comment]
I confirmed that the rendering is OK. Check of the contents looks a bit hard task (maybe it's only I who can review, if any), but I think it is not necessarily essential for publish.

**Comment by takyamamoto** [comment]
This article  contains more equations than other, so I think may be misses. If so, I think who know well will give comments.

**Comment by atamaokac** [comment]
OK..., if you hope so, I will be in charge of the review for the contents. However please do not expect it will be finished so soon.

In general, unless the author hopes a detailed review (like this case), I think we can publish articles after formal & political-correctness checks.

**Comment by takyamamoto** [comment]
I'm so sorry that I'm poor at English. 

数式自体が長いので文字抜けやtypoがあるかもしれないという意味ですが、基本的には無いと思っています（ほとんどの数式は引用している論文に従っているためです）。
NNGPやNTKに関しては専門的に研究しているわけではないので、その分野の研究者が見れば誤っている点（論文の解釈ミス）があるかもしれません。もしあればコメントが貰えるかもしれない (そのためにコメント機能を付けましたが)、という気持ちで書きましたが見返すと言葉足らずが過ぎました。

文献全てに目を通してチェックするのはかなり時間がかかる作業なので、する必要はないと思っています。お願いした（つもりの）checkは日本語的な問題が無いか程度でした。申し訳ないですが…。

**Comment by atamaokac** [comment]
In equation, finding errors (including typo & lack of letters) require understandings of the meaning of the equation themselves. That's why I referred to the review of the whole contents of the article.
Clear & obvious errors are not found at glances in this article. Small poverties in Japanese, if any, do not make problems, unless they may lead to large misunderstandings in political ways.

I believe that this article is enough at the level for publishing on the site, but leave the task for other staffs as a practice.

**Comment by atamaokac** [comment]
I wonder where in the notebook the figure 1_640_50fps_FINAL_VERSION.gif is referred to by {attach} keyword. If not, the file would not be uploaded to the site from the beginning.

**Comment by takyamamoto** [comment]
I fixed, but {attach} keyword shouldn't use in articles from jupyter-notebook because it will be opened in colab. URL of images must be an absolute path.

**Pull request merged**
