### PR TITLE
Add 2019 article, "Graph Neural Network (GNN)をゼロから実装した話"

### PR DESCRIPTION
**Pull request by atamaokac**
Digging of an old article.

This PR should be merged ONLY AFTER the PR #377 has been accepted & successfully merged.

### CODE REVIEW

**Comment by atamaokac** [comment]
Encounter
```
CRITICAL: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408
```

**Comment by atamaokac** [comment]
Gave up to use pdf-img, adding png figures manually. Now it works normally.

Preview:
https://oumpy.github.io/previews/refs/heads/article/GNNfrom0/blog/2019/05/gnnfrom0.html

**Comment by takyamamoto** [comment]
I think it is OK, but if you can, I want you to upload full code of GNN implementation on GitHub.

**Comment by atamaokac** [comment]
The author prepared his repository, and added link to it in the article.

**Comment by atamaokac** [comment]
@takyamamoto Please review again.

**Review by takyamamoto — APPROVED** [review]
OK. Thank you for adding the GitHub repository link.

**Pull request merged**
