### PR TITLE
Auto-publish system replaced by GitHub Actions

### PR DESCRIPTION
**Pull request by atamaokac**
This is a childish implementation of #149. Instead of the present external server, it runs compiling & publishing on a Docker container provided by GitHub Actions. It closes everything within GitHub.

I DON'T KNOW whether it works, largely because I'm very new to GitHub Actions. However I think it is harmless even if it doesn't work.
I temporally stopped the webhook trigger to the external server (set dummy.cgi, rather than the correct deploy.cgi). After some checks which you can, please try.

### CODE REVIEW

**Comment by atamaokac** [comment]
I noticed I'm not confident on runs-on configuration in the workflow file.

**Comment by atamaokac** [comment]
Corrected.

**Comment by takyamamoto** [comment]
This is nice idea and implementation. However, it takes time to review of this pull request. Do you hurry?

**Comment by atamaokac** [comment]
Not at all. If you are kindly willing to give a careful review on it, I turn on the present publishing system. You can (since you have the authority) always turn on/off it by rewriting deploy.cgi/dummy.cgi on the webhook tab in the setting menu of the repository.

**Comment by atamaokac** [comment]
Hmm... It fails in SSH authentication.

**Pull request merged**
