### PR TITLE
News: AtCoder-JSC2023

### PR DESCRIPTION
**Pull request by atamaokac**
Add news of 6th-prize of our leader.

### CODE REVIEW

**Comment by abebe9849** [comment]
Python会会員→弊会会員

**Comment by atamaokac** [comment]
Why?

**Comment by atamaokac** [comment]
> Python会会員→弊会会員

Why?

**Comment by abebe9849** [comment]
会の名前が将来的に阪神タイガースとかに変更になってもブログ記事を修正する必要がなくなるからです

**Comment by atamaokac** [comment]
In general, news articles are "as it is" at the present time. It should not be tampered later, for example when some names are changed in a future, since "it was that name" at that time.
In this sense, some tampering which have been made on some news articles are inappropreate. In PR #493, such ones will be reverted. It is not actually related to the unofficialization of the party. If such tamperings were commanded by the university officers, they are just crazy.

Rather, maybe the author metadata should not be omitted in this news.

**Comment by abebe9849** [comment]
任せます

**Review by Scr1ptKddy — APPROVED** [review]

**Pull request merged**
