### PR TITLE
Rename 'Research tools & techniques' to 'Research tools & topics'.

### PR DESCRIPTION
**Pull request by atamaokac**
@takyamamoto You should include this by yourself in your article PR, or make a separate PR if necessary, whenever you would like to put a new tag.

### CODE REVIEW

**Review by takyamamoto — DISMISSED** [review]
OK. Thanks

**Comment by takyamamoto** [comment]
I understand. I also think `Research tools & techniques` is not a good category name.

**Comment by atamaokac** [comment]
`Research tools & techniques` was renamed to `Research tools & topics`.

**Review by takyamamoto — APPROVED** [review]
Thanks. "Topics" is a good name.

**Pull request merged**
