### PR TITLE
Studymeeting2020

### PR DESCRIPTION
**Pull request by takyamamoto**
I fixed the title 2020-01 to 2020 第一回. The previous title seems to be January 2020.

### CODE REVIEW

**Comment by takyamamoto** [comment]
Conflicting in content/contentconf.py

**Comment by takyamamoto** [comment]
I fixed.

**Comment by atamaokac** [comment]
Resolution of the conflict is wrong. This will fail to work correctly because Pelican tries to regard the attached .ipynb file as a source of another article, because of the lines you deleted.
You must not delete the changes made in `master`, but you should keep BOTH of the changes in the branches which are merged.

And although this is less important, a text file should always be ended by a newline (this is a POSIX Standard. you encounter warnings in many places). I wonder why you dared to delete it.
And please consider again about other insertions of newlines to clarify the changes of text files in diff system.

**Comment by takyamamoto** [comment]
I reverted and fixed.

**Comment by atamaokac** [comment]
The reverse commit erases ALL the changes in the master branch.

Can I fix the merge and force-push it ?

**Comment by atamaokac** [comment]
I pushed branch `article/studymeeting2020_01_atc`, where the merge is corrected and nothing else is done. Please reset `article/studymeeting2020_01` onto it in your local branch & force-push it to remote.

**Comment by takyamamoto** [comment]
OK. Thanks.

**Comment by atamaokac** [comment]
No, just merging `article/studymeetin2020_01` does not solve the problem. It still destroys all the changes in `master`. You need to do as I wrote above.

**Comment by takyamamoto** [comment]
I've lost track of the situation, can't I just close this pull request and create pull request　`article/studymeeting2020_01_atc` ?

**Comment by atamaokac** [comment]
I will fix it instead of you, maybe in the evening. Please wait for that.

**Comment by atamaokac** [comment]
I force-pushed `article/studymeeting2020_01`. You should do either of blow (results are same):
- reset your local `article/studymeeting2020_01` on the remote `article/studymeeting2020_01`
- delete your local `article/studymeeting2020_01`, and pull the remote `article/studymeeting2020_01` to local again.

I pushed another commit on `article/studymeeting2020_01_atc`, on some corrections of newlines. Check and fast-forward it into `article/studymeeting2020_01` if it's ok for you, and make further corrections if there is something left still. After that I will approve & merge it finally.

**Comment by takyamamoto** [comment]
I deleted my local article/studymeeting2020_01. It's ok for me.

**Comment by atamaokac** [comment]
If ok, fast-forward to `article/studymeeting2020_01_atc` and push it to remote `article/studymeeting2020_01`. If you cannot do it due to some technical reason tell me so.

**Comment by takyamamoto** [comment]
Sorry, I didn't know the term "fast-forward merge", but now,  I may understand.

**Comment by atamaokac** [comment]
The last commit is displayed above. It is successfully imported.

**Pull request merged**
