### PR TITLE
Add 2019 article, "基礎配属と企業インターン"

### PR DESCRIPTION
**Pull request by atamaokac**
Digging an old article.

### CODE REVIEW

**Review by abebe9849 — COMMENTED** [review]
自分も教育センター長に問い合わせします。

**Comment by atamaokac** [comment]
@abebe9849 Thanks for your comment, but could you please accept or request changes ?

**Comment by atamaokac** [comment]
Since another old article #376 has been merged, mutual links from/to it has been added to this PR.

**Review by abebe9849 — APPROVED** [review]
approve忘れてました　すいません

**Pull request merged**
