### PR TITLE
Create Linear Mixed Model

### PR DESCRIPTION
**Pull request by takyamamoto**
I converted Takeuchi san's article from PowerPoint to markdown, and this article was checked by Takeuchi san.

Please check.

### CODE REVIEW

**Comment by takyamamoto** [comment]
Thanks. I fixed

**Comment by atamaokac** [comment]
Try merging `master` to `LLM` !
It will show a preview at https://oumpy.github.io/previews/refs/heads/LLM/ .

**Comment by takyamamoto** [comment]
OK. Thanks, It can be seen.
https://oumpy.github.io/previews/refs/heads/LMM/blog/2020/04/linear_mixed_model.html

**Comment by atamaokac** [comment]
@takyamamoto  If you have a corrected version (on t_{ij} definition), please upload.

**Comment by takyamamoto** [comment]
I see, but there is no def of t in original pdf.

**Comment by takyamamoto** [comment]
I heard from Takeuchi san.

**Pull request merged**
