### PR TITLE
Update attention.md

### PR DESCRIPTION
**Pull request by abebe9849**
Title修正
pdfの内容の補足を追加

### CODE REVIEW

**Comment by atamaokac** [comment]
How about renaming to `studymeeting_attention02` or something like that?
(both .md & attach dir.)

**Comment by atamaokac** [comment]
`.md.md` should be `.md`.
directory should also be renamed.

**Comment by abebe9849** [comment]
I would appreciate it if you could change the directory name.

2021年3月19日(金) 15:12 AtamaokaC ***@***.***>:

**Comment by atamaokac** [comment]
@abebe9849 Renaming the dir is on the branch `article/abebe9849-patch-atamaokac`.

You should not use top-level branch name (i.e., always add some directory, in this case `article/`).
Then you do not need to make PR for each correction. You can just add commits to your branch freely.

**Comment by atamaokac** [comment]
Only maintainers (@ldwic03 & @takyamamoto) can directly push & delete the top-level branches.
The other people can only "make" such branches (clearly it is not a good design...).

**Comment by abebe9849** [comment]
I understand, I'll be careful next time.

2021年3月19日(金) 20:51 AtamaokaC ***@***.***>:

**Pull request merged**
