### PR TITLE
Update donations.md

### PR DESCRIPTION
**Pull request by takyamamoto**

### CODE REVIEW

**Review by atamaokac — CHANGES_REQUESTED** [review]
I made some minor corrections on the `page/donation` branch. Check it and fast-forward if you find it's OK.

As I'm repeatedly informing, you must not use top-level branch. After merging, be sure to delete it soon from the repository.

**Comment by atamaokac** [comment]
Note: How about the order? It does not seem to be time-ordering.

**Comment by takyamamoto** [comment]
Thank you for your modification. I have no problem with the change. The names are sorted by position.

**Comment by takyamamoto** [comment]
I sorted the names by the date of donation.

**Pull request merged**
