### PR TITLE
update achievements.md: ikra_jishuken

### PR DESCRIPTION
**Pull request by takyamamoto**

### CODE REVIEW

**Comment by atamaokac** [comment]
I'll propose some corrections tomorrow.

**Comment by takyamamoto** [comment]
I think the link to "achievements/07_igakubu.pdf" is not proper. In the preview, the pdf link functioned when using <a> tag.

**Comment by atamaokac** [comment]
The preview is not fully updated following the source. It sometimes happen, for unknown reason. Do you also have an error on your local environment?

**Comment by atamaokac** [comment]
I canceled the commits from `ikra` branch to revert the preview, and my commits are now on branch `ikra_atamaokac` with a preview
https://oumpy.github.io/previews/refs/heads/origin/page/achievements/ikra_atamaokac/

Check it and fast-forward again if no problems.

**Comment by takyamamoto** [comment]
OK.

**Review by ykohki — APPROVED** [review]

**Review by ykohki — APPROVED** [review]

**Pull request merged**
